header: 
  version: 11

# Build target, machine, distro
distro: "meta-techleef-distro"
machine: "qemux86-64" 
target: "core-image-minimal"


env:
  YOCTO_BRANCH: "${YOCTO_BRANCH:=scarthgap}"


repos:
  poky:
    url: "https://git.yoctoproject.org/poky"
    refspec: "${YOCTO_BRANCH}"
    layers:
      meta: true
      meta-poky: true
      meta-yocto-bsp: true

  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded.git"
    refspec: "${YOCTO_BRANCH}"
    layers:
      meta-oe: true
      meta-python: true
      meta-networking: true

  meta-techleef-bsp:
    path: "../meta-techleef-bsp"
    layers:
      meta-techleef-bsp: true

  meta-techleef-distro:
    path: "../meta-techleef-distro"
    layers:
      meta-techleef-distro: true

  meta-techleef-prj:
    path: "../meta-techleef-prj"
    layers:
      meta-techleef-prj: true


includes:
  - "kas/local.yml"

